require("themery").setup({
	themes = {
		"nightblossom",
		"nightblossom-sakura",
		"nightblossom-pastel",
		"vscode",
		"gruvbox-material",
		"miasma",
		"cyberdream",
		"kurayami",
		"catppuccin",
		-- "shado",
		"shado-legacy",
	    -- "shado",
        "nightblossom",
        "nightblossom-pastel",
        "nightblossom-sakura",
	    "shado-legacy",
	},
	livepreview = true,
})
